x=msgbox("Your Text Here" ,0, "Your Title Here") 
x=msgbox("Your Text Here" ,0, "Your Title Here") 
x=msgbox("Your Text Here" ,0, "Your Title Here") 
x=msgbox("Your Text Here" ,0, "Your Title Here") 
x=msgbox("Your Text Here" ,0, "Your Title Here") 
x=msgbox("Your Text Here" ,4, "Your Title Here") 
x=msgbox("Your Text Here" ,4, "Your Title Here") 
x=msgbox("Your Text Here" ,4, "Your Title Here") 
